---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/elsaagne/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp css/* $DEPLOYPATH/css
    - /bin/cp js/* $DEPLOYPATH/js
    - /bin/cp img/* $DEPLOYPATH/img
